### ISSUE TITLE
Blazor - Can't resolve registered instance from tenant container

### ISSUE THREAD

**Issue by jgarner1** [autofac/Autofac.AspNetCore.Multitenant#25]
I am in the process of creating a multi tenant app using Blazor and .net core 3.1. I used the sample Blazor application to create a modified version for multi tenant using the WeatherForecastService as the tenant specific instance.

Resolving the WeatherForecastService however throws an exception causing the circuit to fail. I have created a demo of the issue here https://github.com/jgarner1/autofac.multitenant.blazor

Your help will be much appreciated.

**Comment by jgarner1** [comment]
Anyone?

**Comment by alsami** [comment]
I try looking into it today. Would you mind posting the stacktrace?

**Comment by jgarner1** [comment]
System.InvalidOperationException: Cannot provide a value for property 'ForecastService' on type 'BlazorMultiTenantApp.Pages.FetchData'. There is no registered service of type 'BlazorMultiTenantApp.Data.WeatherForecastService'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass5_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'RbGiLL0I8kcIumy0KLKYv8BXsMgnYYicTqe-L5DhMaw'.

**Comment by jgarner1** [comment]
I believe this happens possibly because it is trying to resolve from the parent container but should be looking at the tenant container, but you will see when you run the demo app.

**Comment by alsami** [comment]
> I believe this happens possibly because it is trying to resolve from the parent container but should be looking at the tenant container, but you will see when you run the demo app.

I think the issue lies [here](https://github.com/jgarner1/autofac.multitenant.blazor/blob/master/BlazorMultiTenantApp/Startup.cs#L30). You don't have a registration for an unidentified tenant.

Checkout the [sandbox sample](https://github.com/autofac/Autofac.AspNetCore.Multitenant/blob/develop/samples/Sandbox.Shared/ContainerSetup.cs#L9) again, it always has a default implementation for when a tenant cannot be identified.

**Comment by jgarner1** [comment]
OK, missed that! Thank you very much.
