### ISSUE TITLE
Supporting netcoreapp3.0/netstandard2.1?

### ISSUE THREAD

**Issue by saber-wang** [autofac/Autofac.AspNetCore.Multitenant#9]
`fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLP5SG5BH8U4", Request id "0HLP5SG5BH8U4:00000001": An unhandled exception was thrown by the application.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Hosting.Internal.RequestServicesFeature' from assembly 'Microsoft.AspNetCore.Hosting, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Autofac.Integration.AspNetCore.Multitenant.RequestServicesFeatureFactory.GenerateLambda()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Autofac.Integration.AspNetCore.Multitenant.RequestServicesFeatureFactory.CreateFeature(HttpContext context, IServiceScopeFactory scopeFactory) in E:\源码\Autofac.AspNetCore.Multitenant\src\Autofac.Integration.AspNetCore.Multitenant\RequestServicesFeatureFactory.cs:line 18
   at Autofac.Integration.AspNetCore.Multitenant.MultitenantRequestServicesMiddleware.Invoke(HttpContext context) in E:\源码\Autofac.AspNetCore.Multitenant\src\Autofac.Integration.AspNetCore.Multitenant\MultitenantRequestServicesMiddleware.cs:line 64
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

**Comment by alsami** [comment]
Hey, we are working on it. There is another issue [here](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/36). For now you will have to stick to ASP.NET Core 2.2.

**Comment by tillig** [comment]
Published as 2.0.0-rc1, will release 2.0.0 when .NET Core 3 is out of preview.
